# Generated by Django 5.0 on 2023-12-29 18:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.UUIDField(default=uuid.UUID('574e1022-4586-417d-aaf9-4bb3a2eea275'), primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='Name', max_length=50)),
                ('last_name', models.CharField(default='Name', max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='nil', max_length=14, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?1?\\d{9,15}$')])),
                ('password', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dow', models.CharField(default='Not applicable', max_length=50)),
                ('category', models.CharField(default='Others', max_length=50)),
                ('has_deadline', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.userprofile')),
            ],
        ),
    ]
