# Generated by Django 5.0 on 2023-12-19 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='compass.basemodel')),
                ('user_id', models.UUIDField(default=uuid.UUID('74b3cb30-527b-495b-b200-d59dcc356ed1'), primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='Name', max_length=50)),
                ('last_name', models.CharField(default='Name', max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_age', models.IntegerField()),
                ('user_ed_level', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.CharField(max_length=50)),
            ],
            bases=('compass.basemodel',),
        ),
        migrations.CreateModel(
            name='DailyAgenda',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compass.basemodel')),
                ('dow', models.CharField(default='Not applicable', max_length=50)),
                ('category', models.CharField(default='Others', max_length=50)),
                ('has_deadline', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.user')),
            ],
            bases=('compass.basemodel',),
        ),
    ]
