# Generated by Django 5.0 on 2024-01-04 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyagenda',
            name='tasks',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('09fff279-e8ac-490a-b575-6a6199b0dbc6'), primary_key=True, serialize=False, unique=True),
        ),
    ]
