# Generated by Django 5.0 on 2023-12-20 01:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_user_dailyagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('5bb7b35e-049e-4fd0-8e19-51ab95cb3b8a'), primary_key=True, serialize=False, unique=True),
        ),
    ]
