# Generated by Django 5.0 on 2023-12-20 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='compass.basemodel')),
                ('user_id', models.UUIDField(default=uuid.UUID('c12d1bca-fd6f-4e0d-ad5b-6b950ab0b0f3'), primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(default='Name', max_length=50)),
                ('last_name', models.CharField(default='Name', max_length=50)),
                ('userame', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('ed_level', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=50)),
            ],
            bases=('compass.basemodel',),
        ),
        migrations.AlterField(
            model_name='dailyagenda',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compass.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
