# Generated by Django 5.0 on 2023-12-24 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0004_userprofile_alter_dailyagenda_user_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('9baf628c-16ba-477e-8817-4842359fde83'), primary_key=True, serialize=False, unique=True),
        ),
    ]
