# Generated by Django 5.0 on 2023-12-24 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0005_alter_userprofile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('c4a2ba90-3701-4153-815e-b1f474a07c77'), primary_key=True, serialize=False, unique=True),
        ),
    ]
